namespace GerberViewer.Views
{
    partial class AlignStitchingControl
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Label lblTitle, lblSampleRaster, lblLastOutput, lblImageCount;
        private System.Windows.Forms.Button btnSelectManifest, btnOpenImageFolder, btnSelectOutputFolder, btnRunAlignStitch, btnCancelAlignStitch;
        private System.Windows.Forms.TextBox txtManifestPath, txtManifestInfo, txtImageFolder, txtOutputFolder, txtDiagnostics;
        private System.Windows.Forms.ListBox lstCapturedImages, lstTab3Log;
        private System.Windows.Forms.ProgressBar prgAlignStitch;
        private System.Windows.Forms.TabControl resultTabControl;
        private System.Windows.Forms.TabPage tabOrderView, tabDiagnostics, tabStitchedImage, tabComparison, tabLogs;
        private System.Windows.Forms.PropertyGrid alignConfigGrid;
        private GerberViewer.Stitching.DesignControls.PathCanvasControl orderPathCanvas;
        private System.Windows.Forms.PictureBox picStitchedImage, picComparison;

        private void InitializeComponent()
        {
            this.lblTitle = new System.Windows.Forms.Label(); this.lblSampleRaster = new System.Windows.Forms.Label(); this.lblLastOutput = new System.Windows.Forms.Label();
            this.btnSelectManifest = new System.Windows.Forms.Button(); this.txtManifestPath = new System.Windows.Forms.TextBox(); this.txtManifestInfo = new System.Windows.Forms.TextBox();
            this.btnOpenImageFolder = new System.Windows.Forms.Button(); this.txtImageFolder = new System.Windows.Forms.TextBox(); this.btnSelectOutputFolder = new System.Windows.Forms.Button(); this.txtOutputFolder = new System.Windows.Forms.TextBox();
            this.lstCapturedImages = new System.Windows.Forms.ListBox(); this.lblImageCount = new System.Windows.Forms.Label(); this.btnRunAlignStitch = new System.Windows.Forms.Button(); this.btnCancelAlignStitch = new System.Windows.Forms.Button(); this.prgAlignStitch = new System.Windows.Forms.ProgressBar();
            this.alignConfigGrid = new System.Windows.Forms.PropertyGrid(); this.resultTabControl = new System.Windows.Forms.TabControl(); this.tabOrderView = new System.Windows.Forms.TabPage(); this.tabDiagnostics = new System.Windows.Forms.TabPage(); this.tabStitchedImage = new System.Windows.Forms.TabPage(); this.tabComparison = new System.Windows.Forms.TabPage(); this.tabLogs = new System.Windows.Forms.TabPage();
            this.orderPathCanvas = new GerberViewer.Stitching.DesignControls.PathCanvasControl(); this.txtDiagnostics = new System.Windows.Forms.TextBox(); this.picStitchedImage = new System.Windows.Forms.PictureBox(); this.picComparison = new System.Windows.Forms.PictureBox(); this.lstTab3Log = new System.Windows.Forms.ListBox();
            this.resultTabControl.SuspendLayout(); this.tabOrderView.SuspendLayout(); this.tabDiagnostics.SuspendLayout(); this.tabStitchedImage.SuspendLayout(); this.tabComparison.SuspendLayout(); this.tabLogs.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)(this.picStitchedImage)).BeginInit(); ((System.ComponentModel.ISupportInitialize)(this.picComparison)).BeginInit(); this.SuspendLayout();
            this.lblTitle.AutoSize = true; this.lblTitle.Location = new System.Drawing.Point(16, 12); this.lblTitle.Text = "Align and Stitching workflow";
            this.lblSampleRaster.AutoSize = true; this.lblSampleRaster.Location = new System.Drawing.Point(16, 36); this.lblSampleRaster.Text = "Source sample raster: -";
            this.lblLastOutput.AutoSize = true; this.lblLastOutput.Location = new System.Drawing.Point(16, 58); this.lblLastOutput.Text = "Last stitched output: -";
            this.btnSelectManifest.Location = new System.Drawing.Point(16, 84); this.btnSelectManifest.Size = new System.Drawing.Size(130, 28); this.btnSelectManifest.Text = "Select Manifest"; this.btnSelectManifest.Click += new System.EventHandler(this.btnSelectManifest_Click);
            this.txtManifestPath.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right))); this.txtManifestPath.Location = new System.Drawing.Point(152, 88); this.txtManifestPath.ReadOnly = true; this.txtManifestPath.Size = new System.Drawing.Size(616, 22);
            this.txtManifestInfo.Location = new System.Drawing.Point(16, 118); this.txtManifestInfo.Multiline = true; this.txtManifestInfo.ReadOnly = true; this.txtManifestInfo.ScrollBars = System.Windows.Forms.ScrollBars.Vertical; this.txtManifestInfo.Size = new System.Drawing.Size(280, 96);
            this.btnOpenImageFolder.Location = new System.Drawing.Point(302, 118); this.btnOpenImageFolder.Size = new System.Drawing.Size(150, 28); this.btnOpenImageFolder.Text = "Select Captured Folder"; this.btnOpenImageFolder.Click += new System.EventHandler(this.btnOpenImageFolder_Click);
            this.txtImageFolder.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right))); this.txtImageFolder.Location = new System.Drawing.Point(458, 122); this.txtImageFolder.ReadOnly = true; this.txtImageFolder.Size = new System.Drawing.Size(310, 22);
            this.btnSelectOutputFolder.Location = new System.Drawing.Point(302, 152); this.btnSelectOutputFolder.Size = new System.Drawing.Size(150, 28); this.btnSelectOutputFolder.Text = "Select Output Folder"; this.btnSelectOutputFolder.Click += new System.EventHandler(this.btnSelectOutputFolder_Click);
            this.txtOutputFolder.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right))); this.txtOutputFolder.Location = new System.Drawing.Point(458, 156); this.txtOutputFolder.ReadOnly = true; this.txtOutputFolder.Size = new System.Drawing.Size(310, 22);
            this.lblImageCount.AutoSize = true; this.lblImageCount.Location = new System.Drawing.Point(302, 190); this.lblImageCount.Text = "Images: 0";
            this.btnRunAlignStitch.Location = new System.Drawing.Point(408, 184); this.btnRunAlignStitch.Size = new System.Drawing.Size(120, 28); this.btnRunAlignStitch.Text = "Run Align/Stitch"; this.btnRunAlignStitch.Click += new System.EventHandler(this.btnRunAlignStitch_Click);
            this.btnCancelAlignStitch.Enabled = false; this.btnCancelAlignStitch.Location = new System.Drawing.Point(534, 184); this.btnCancelAlignStitch.Size = new System.Drawing.Size(80, 28); this.btnCancelAlignStitch.Text = "Cancel"; this.btnCancelAlignStitch.Click += new System.EventHandler(this.btnCancelAlignStitch_Click);
            this.prgAlignStitch.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right))); this.prgAlignStitch.Location = new System.Drawing.Point(620, 188); this.prgAlignStitch.Size = new System.Drawing.Size(148, 20);
            this.lstCapturedImages.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left))); this.lstCapturedImages.Location = new System.Drawing.Point(16, 220); this.lstCapturedImages.Size = new System.Drawing.Size(280, 228);
            this.alignConfigGrid.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left))); this.alignConfigGrid.Location = new System.Drawing.Point(302, 220); this.alignConfigGrid.Size = new System.Drawing.Size(230, 228);
            this.resultTabControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right))); this.resultTabControl.Controls.Add(this.tabOrderView); this.resultTabControl.Controls.Add(this.tabDiagnostics); this.resultTabControl.Controls.Add(this.tabStitchedImage); this.resultTabControl.Controls.Add(this.tabComparison); this.resultTabControl.Controls.Add(this.tabLogs); this.resultTabControl.Location = new System.Drawing.Point(538, 220); this.resultTabControl.Size = new System.Drawing.Size(230, 228);
            this.tabOrderView.Text = "Order and Status"; this.tabOrderView.Controls.Add(this.orderPathCanvas); this.orderPathCanvas.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabDiagnostics.Text = "Alignment Diagnostics"; this.tabDiagnostics.Controls.Add(this.txtDiagnostics); this.txtDiagnostics.Dock = System.Windows.Forms.DockStyle.Fill; this.txtDiagnostics.Multiline = true; this.txtDiagnostics.ReadOnly = true; this.txtDiagnostics.Text = "OrderIndex, Row/Column, paths, NCC, ECC, CapturedToSampleTransform, pose source and rejection reason appear in logs/report.";
            this.tabStitchedImage.Text = "Stitched Result"; this.tabStitchedImage.Controls.Add(this.picStitchedImage); this.picStitchedImage.Dock = System.Windows.Forms.DockStyle.Fill; this.picStitchedImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.tabComparison.Text = "Sample Comparison"; this.tabComparison.Controls.Add(this.picComparison); this.picComparison.Dock = System.Windows.Forms.DockStyle.Fill; this.picComparison.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.tabLogs.Text = "Logs"; this.tabLogs.Controls.Add(this.lstTab3Log); this.lstTab3Log.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Controls.Add(this.resultTabControl); this.Controls.Add(this.alignConfigGrid); this.Controls.Add(this.prgAlignStitch); this.Controls.Add(this.btnCancelAlignStitch); this.Controls.Add(this.btnRunAlignStitch); this.Controls.Add(this.lblImageCount); this.Controls.Add(this.lstCapturedImages); this.Controls.Add(this.txtOutputFolder); this.Controls.Add(this.btnSelectOutputFolder); this.Controls.Add(this.txtImageFolder); this.Controls.Add(this.btnOpenImageFolder); this.Controls.Add(this.txtManifestInfo); this.Controls.Add(this.txtManifestPath); this.Controls.Add(this.btnSelectManifest); this.Controls.Add(this.lblLastOutput); this.Controls.Add(this.lblSampleRaster); this.Controls.Add(this.lblTitle); this.Name = "AlignStitchingControl"; this.Size = new System.Drawing.Size(800, 500);
            this.resultTabControl.ResumeLayout(false); this.tabOrderView.ResumeLayout(false); this.tabDiagnostics.ResumeLayout(false); this.tabDiagnostics.PerformLayout(); this.tabStitchedImage.ResumeLayout(false); this.tabComparison.ResumeLayout(false); this.tabLogs.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)(this.picStitchedImage)).EndInit(); ((System.ComponentModel.ISupportInitialize)(this.picComparison)).EndInit(); this.ResumeLayout(false); this.PerformLayout();
        }
    }
}
